version: "3.7"
services:
  plex-export:
    image: plex-export:1.0.0
    container_name: plex-export
    hostname: plex-export
    restart: always
    #networks:
      #traefik_proxy:
        #ipv4_address: 172.16.1.80
    ports:
      - "80:80"
    security_opt:
      - no-new-privileges:true
    environment:
      - PLEX_URL=url_here
      - PLEX_TOKEN=token_here
      - PHP_DATE_TIMEZONE=America/Chicago
      - REFRESH_RATE=300 # 5 Minutes

#networks:
  #traefik_proxy:
    #external: true